id: I628E3454
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:34:44+00:00'
last_modified: '2022-06-08T14:31:10.696635+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20257
  title: སྨན་གྱི་འཁྲུངས་དཔེ་གནད་བསྡུས་བདུད་རྩིའི་ཐིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    0E78:
      image_group_id: I8LS20259
      title: ''
      total_pages: 249
      order: 1
      base_file: 0E78.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
