id: P010563
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20257
  title: སྨན་གྱི་འཁྲུངས་དཔེ་གནད་བསྡུས་བདུད་རྩིའི་ཐིགས་པ།
  author: ''
  volumes:
    81ca29fe341a4afeacef26c4633a5f15:
      image_group_id: I8LS20259
      title: ''
      volume_number: 1
      total_pages: 249
      base_file: v001.txt
